site_name: Campaign Insight Accelerator
site_description: Documentation for the Campaign Insight Accelerator platform
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference: api.md
  - Development: development.md 